from pathlib import Path

import pandas as pd


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

REPORTS_DIR = PROJECT_ROOT / "reports"

BASELINE_METRICS_PATH = (
    REPORTS_DIR / "baseline_rul_metrics.csv"
)

XGBOOST_METRICS_PATH = (
    REPORTS_DIR / "xgboost_rul_metrics.csv"
)

OUTPUT_PATH = (
    REPORTS_DIR / "model_comparison.csv"
)


# ============================================================
# LOAD METRICS
# ============================================================

def load_metrics() -> pd.DataFrame:
    """Load metrics generated by the trained models."""

    if not BASELINE_METRICS_PATH.exists():
        raise FileNotFoundError(
            f"Baseline metrics not found: "
            f"{BASELINE_METRICS_PATH}"
        )

    if not XGBOOST_METRICS_PATH.exists():
        raise FileNotFoundError(
            f"XGBoost metrics not found: "
            f"{XGBOOST_METRICS_PATH}"
        )

    baseline = pd.read_csv(
        BASELINE_METRICS_PATH
    )

    xgboost = pd.read_csv(
        XGBOOST_METRICS_PATH
    )

    metrics = pd.concat(
        [baseline, xgboost],
        ignore_index=True,
    )

    return metrics


# ============================================================
# CREATE COMPARISON
# ============================================================

def create_comparison(
    metrics: pd.DataFrame,
) -> pd.DataFrame:
    """Create model comparison with improvement metrics."""

    baseline = metrics[
        metrics["model"] == "RandomForestBaseline"
    ].iloc[0]

    xgboost = metrics[
        metrics["model"] == "XGBoost"
    ].iloc[0]

    mae_improvement = (
        baseline["MAE"] - xgboost["MAE"]
    )

    rmse_improvement = (
        baseline["RMSE"] - xgboost["RMSE"]
    )

    mae_improvement_pct = (
        mae_improvement
        / baseline["MAE"]
        * 100
    )

    rmse_improvement_pct = (
        rmse_improvement
        / baseline["RMSE"]
        * 100
    )

    comparison = pd.DataFrame(
        [
            {
                "baseline_model": "RandomForestBaseline",
                "candidate_model": "XGBoost",
                "baseline_MAE": baseline["MAE"],
                "XGBoost_MAE": xgboost["MAE"],
                "MAE_improvement": mae_improvement,
                "MAE_improvement_pct": mae_improvement_pct,
                "baseline_RMSE": baseline["RMSE"],
                "XGBoost_RMSE": xgboost["RMSE"],
                "RMSE_improvement": rmse_improvement,
                "RMSE_improvement_pct": rmse_improvement_pct,
                "validation_samples": int(
                    xgboost["samples"]
                ),
            }
        ]
    )

    return comparison


# ============================================================
# SAVE REPORT
# ============================================================

def save_comparison(
    comparison: pd.DataFrame,
) -> None:
    """Save model comparison report."""

    REPORTS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    comparison.to_csv(
        OUTPUT_PATH,
        index=False,
    )


# ============================================================
# MAIN
# ============================================================

def main():
    """Generate final Day 4 model comparison."""

    print("\nRUL MODEL COMPARISON")
    print("=" * 70)

    metrics = load_metrics()

    print("\nMODEL METRICS")
    print("-" * 70)

    print(
        metrics.to_string(
            index=False
        )
    )

    comparison = create_comparison(
        metrics
    )

    save_comparison(
        comparison
    )

    result = comparison.iloc[0]

    print("\nCOMPARISON")
    print("-" * 70)

    print(
        f"Baseline MAE       : "
        f"{result['baseline_MAE']:.4f}"
    )

    print(
        f"XGBoost MAE        : "
        f"{result['XGBoost_MAE']:.4f}"
    )

    print(
        f"MAE improvement    : "
        f"{result['MAE_improvement']:.4f}"
    )

    print(
        f"MAE improvement %  : "
        f"{result['MAE_improvement_pct']:.2f}%"
    )

    print(
        f"\nBaseline RMSE      : "
        f"{result['baseline_RMSE']:.4f}"
    )

    print(
        f"XGBoost RMSE       : "
        f"{result['XGBoost_RMSE']:.4f}"
    )

    print(
        f"RMSE improvement   : "
        f"{result['RMSE_improvement']:.4f}"
    )

    print(
        f"RMSE improvement % : "
        f"{result['RMSE_improvement_pct']:.2f}%"
    )

    print(
        f"\nValidation samples : "
        f"{int(result['validation_samples'])}"
    )

    print(
        f"\nSaved comparison:\n"
        f"{OUTPUT_PATH}"
    )


if __name__ == "__main__":
    main()